import { NextResponse } from 'next/server';
import { fal } from '@fal-ai/client';

export const runtime = 'edge';

/**
 * Custom Vercel AI Gateway implementation for SubForge.
 * 
 * Maps the generic model ID 'black-forest-labs/flux-1.1-pro' 
 * to the actual provider endpoint.
 */
export async function POST(req: Request) {
  try {
    const { prompt, n = 1, model } = await req.json();

    if (model !== 'black-forest-labs/flux-1.1-pro') {
      return NextResponse.json({ 
        error: { message: `Model '${model}' not found in this gateway.`, type: 'model_not_found' } 
      }, { status: 404 });
    }

    if (!process.env.FAL_KEY) {
      return NextResponse.json({ 
        error: { message: 'FAL_KEY not configured on server.', type: 'invalid_request_error' } 
      }, { status: 500 });
    }

    // Configure fal
    fal.config({ credentials: process.env.FAL_KEY });

    // Execute generation via Fal (Flux Pro 1.1)
    const result = (await fal.subscribe('fal-ai/flux-pro/v1.1', {
      input: {
        prompt: prompt,
        image_size: 'square_hd',
        num_images: n,
      },
    })) as any;

    const imageUrl = result?.images?.[0]?.url;

    if (!imageUrl) {
      return NextResponse.json({ 
        error: { message: 'No image generated by the underlying model.', type: 'api_error' } 
      }, { status: 500 });
    }

    // Return in the format expected by the AI SDK's Vercel AI Gateway
    return NextResponse.json({
      images: [
        {
          url: imageUrl,
          // We could fetch and convert to base64 here if needed for binary response,
          // but typically the URL is sufficient for client display.
        }
      ]
    });

  } catch (error: any) {
    console.error('Gateway Error:', error);
    return NextResponse.json({ 
      error: { message: error.message || 'Internal gateway error', type: 'internal_server_error' } 
    }, { status: 500 });
  }
}
